branches:
  only:
  - develop
  - master
skip_tags: true
image: Visual Studio 2017
skip_commits:
  files:
    - docs/*
    - '**/*.html'
    - '**/*.md'
build_script:
- cmd: >-
    @echo off

    cls

    If Not Exist src\.nuget\nuget.exe msbuild src\.nuget\NuGet.targets -Target:RestorePackages

    If Not Exist src\packages\FAKE\tools\fake.exe src\.nuget\nuget.exe Install FAKE -OutputDirectory "src\packages" -ExcludeVersion

    src\packages\FAKE\tools\fake.exe build.fsx %*
test:
  assemblies:
  - src/Machete.Tests/bin/Release/net452/Machete.Tests.dll
  - src/Machete.HL7.Tests/bin/Release/net452/Machete.HL7.Tests.dll
  - src/Machete.X12.Tests/bin/Release/net452/Machete.X12.Tests.dll
  categories:
    except:
    - SlowAF
artifacts:
- path: build_artifacts/*.nupkg
  name: Packages
deploy:
- provider: NuGet
  name: Prerelease
  api_key:
    secure: BWMOFDajbQuOfkMI0W01vsyQcESgdxsDK2kYD0QSeuG7BKece85l+99VGzZvjLJt
  on:
    branch: develop
- provider: NuGet
  name: Release
  api_key:
    secure: BWMOFDajbQuOfkMI0W01vsyQcESgdxsDK2kYD0QSeuG7BKece85l+99VGzZvjLJt
  on:
    branch: master
  